### ISSUE TITLE
[STABLE] Sign In SRMOne 

### ISSUE THREAD

**Issue by adityathakurxd** [AV-Studios/SRMOne#30]
There would be two modes of sign-in. One would be using the SRM University domain id. The other is either google or apple id depending on the OS.

### Design
![Untitled-2022-01-12-2204](https://user-images.githubusercontent.com/53579386/149183845-ee653890-1c76-412a-8cf3-0f8ec0b8ff2b.png)

### Tasks

- [ ] Create an Onboarding Screen
- [ ] Sign in with SRM Email Screen that has a text input box
- [ ] Validate email (stu.srmuniversity.ac.in)
- [ ] Send verification email and go to next screen only if verified
- [ ] Add a select username option
- [ ] Get year of enrollment from email
- [ ] Add Google or Apple ID option based on OS
- [ ] Proceed to next screen on successful sign in

**Comment by adityathakurxd** [comment]
**Priority Issue **

The Google/Apple Sign In can redirect to locked - Notes Only view.

While the stu.uni sign in could save emails, use Regular Expression to get 1st name and save profile.

- Named won't be editable to prevent fake profiles
